// Template de checklist de obra residencial — se precarga al inicializar
export const FASES = [
  { num: 1,  label: 'Pre-construcción',       color: '#6366f1' },
  { num: 2,  label: 'Demolición y Preparación', color: '#64748b' },
  { num: 3,  label: 'Estructura',             color: '#ef4444' },
  { num: 4,  label: 'Cerramientos',           color: '#f97316' },
  { num: 5,  label: 'Instalaciones',          color: '#eab308' },
  { num: 6,  label: 'Revoques y Contrapisos', color: '#84cc16' },
  { num: 7,  label: 'Definiciones de Diseño', color: '#ec4899' },
  { num: 8,  label: 'Terminaciones',          color: '#14b8a6' },
  { num: 9,  label: 'Exteriores',             color: '#06b6d4' },
  { num: 10, label: 'Cierre y Entrega',       color: '#8b5cf6' },
];

export const TIPOS_TAREA = {
  definicion:   { label: 'Definición',   color: '#818cf8', icon: '📋' },
  compra:       { label: 'Compra',       color: '#fbbf24', icon: '🛒' },
  ejecucion:    { label: 'Ejecución',    color: '#34d399', icon: '🔨' },
  verificacion: { label: 'Verificación', color: '#f472b6', icon: '✅' },
};

export const ESTADOS = {
  pendiente:  { label: 'Pendiente',  color: '#64748b', bg: 'rgba(100,116,139,0.1)' },
  en_proceso: { label: 'En Proceso', color: '#3b82f6', bg: 'rgba(59,130,246,0.1)' },
  completada: { label: 'Completada', color: '#22c55e', bg: 'rgba(34,197,94,0.1)' },
  bloqueada:  { label: 'Bloqueada',  color: '#ef4444', bg: 'rgba(239,68,68,0.1)' },
};

// ~80 tareas organizadas por fase
export const TEMPLATE_TAREAS = [
  // FASE 1
  { codigo:'1.1', titulo:'Estudio de suelos / geotecnia',                faseNum:1, tipo:'definicion',  leadTimeDias:15, responsableTipo:'Proyecto' },
  { codigo:'1.2', titulo:'Relevamiento topográfico',                     faseNum:1, tipo:'definicion',  leadTimeDias:10, responsableTipo:'Proyecto' },
  { codigo:'1.3', titulo:'Proyecto ejecutivo completo',                  faseNum:1, tipo:'definicion',  leadTimeDias:0,  responsableTipo:'Proyecto' },
  { codigo:'1.4', titulo:'Tramitar permiso de construcción',             faseNum:1, tipo:'definicion',  leadTimeDias:60, responsableTipo:'Admin' },
  { codigo:'1.5', titulo:'Contratar seguro de obra (ART/RC)',            faseNum:1, tipo:'definicion',  leadTimeDias:7,  responsableTipo:'Admin' },
  { codigo:'1.6', titulo:'Firmar contrato con contratista general',      faseNum:1, tipo:'definicion',  leadTimeDias:0,  responsableTipo:'Director' },
  { codigo:'1.7', titulo:'Definir presupuesto y plan de pagos',          faseNum:1, tipo:'definicion',  leadTimeDias:0,  responsableTipo:'Director' },
  { codigo:'1.8', titulo:'Contratar obrador provisorio',                 faseNum:1, tipo:'compra',      leadTimeDias:7,  responsableTipo:'Campo' },
  // FASE 2
  { codigo:'2.1', titulo:'Vallado perimetral y cartelería',              faseNum:2, tipo:'ejecucion',   leadTimeDias:3,  responsableTipo:'Campo' },
  { codigo:'2.2', titulo:'Demolición (si aplica)',                       faseNum:2, tipo:'ejecucion',   leadTimeDias:0,  responsableTipo:'Contratista' },
  { codigo:'2.3', titulo:'Retiro de escombros',                          faseNum:2, tipo:'ejecucion',   leadTimeDias:0,  responsableTipo:'Contratista' },
  { codigo:'2.4', titulo:'Limpieza y nivelación del terreno',            faseNum:2, tipo:'ejecucion',   leadTimeDias:0,  responsableTipo:'Contratista' },
  // FASE 3
  { codigo:'3.1', titulo:'Excavación de cimientos',                      faseNum:3, tipo:'ejecucion',   leadTimeDias:0,  responsableTipo:'Contratista' },
  { codigo:'3.2', titulo:'Armado hierro y encofrado bases',              faseNum:3, tipo:'ejecucion',   leadTimeDias:0,  responsableTipo:'Contratista' },
  { codigo:'3.3', titulo:'Hormigonado de cimientos',                     faseNum:3, tipo:'ejecucion',   leadTimeDias:0,  responsableTipo:'Contratista' },
  { codigo:'3.4', titulo:'Mampostería de elevación',                     faseNum:3, tipo:'ejecucion',   leadTimeDias:0,  responsableTipo:'Contratista' },
  { codigo:'3.5', titulo:'Columnas y vigas',                             faseNum:3, tipo:'ejecucion',   leadTimeDias:0,  responsableTipo:'Contratista' },
  { codigo:'3.6', titulo:'Encofrado y hormigonado de losa',              faseNum:3, tipo:'ejecucion',   leadTimeDias:0,  responsableTipo:'Contratista' },
  { codigo:'3.7', titulo:'Verificar aplomado y niveles',                 faseNum:3, tipo:'verificacion',leadTimeDias:0,  responsableTipo:'Campo' },
  { codigo:'3.8', titulo:'Impermeabilización losa/muros',                faseNum:3, tipo:'ejecucion',   leadTimeDias:0,  responsableTipo:'Contratista' },
  // FASE 4
  { codigo:'4.1', titulo:'Definir aberturas (tipo, medidas, material)',  faseNum:4, tipo:'definicion',  leadTimeDias:45, responsableTipo:'Proyecto' },
  { codigo:'4.2', titulo:'Comprar aberturas / ventanas',                 faseNum:4, tipo:'compra',      leadTimeDias:45, responsableTipo:'Admin' },
  { codigo:'4.3', titulo:'Colocación de premarcos',                      faseNum:4, tipo:'ejecucion',   leadTimeDias:0,  responsableTipo:'Contratista' },
  { codigo:'4.4', titulo:'Mampostería cerramientos exteriores',          faseNum:4, tipo:'ejecucion',   leadTimeDias:0,  responsableTipo:'Contratista' },
  { codigo:'4.5', titulo:'Tabiques divisorios interiores',               faseNum:4, tipo:'ejecucion',   leadTimeDias:0,  responsableTipo:'Contratista' },
  { codigo:'4.6', titulo:'Verificar vanos y medidas aberturas',          faseNum:4, tipo:'verificacion',leadTimeDias:0,  responsableTipo:'Campo' },
  // FASE 5
  { codigo:'5.1', titulo:'Inst. eléctrica: cañerías y cajas',           faseNum:5, tipo:'ejecucion',   leadTimeDias:0,  responsableTipo:'Electricista' },
  { codigo:'5.2', titulo:'Inst. sanitaria: desagües',                    faseNum:5, tipo:'ejecucion',   leadTimeDias:0,  responsableTipo:'Plomero' },
  { codigo:'5.3', titulo:'Inst. agua fría y caliente',                   faseNum:5, tipo:'ejecucion',   leadTimeDias:0,  responsableTipo:'Plomero' },
  { codigo:'5.4', titulo:'Instalación de gas',                           faseNum:5, tipo:'ejecucion',   leadTimeDias:0,  responsableTipo:'Gasista' },
  { codigo:'5.5', titulo:'Inst. A/A (cañerías)',                         faseNum:5, tipo:'ejecucion',   leadTimeDias:0,  responsableTipo:'Climatización' },
  { codigo:'5.6', titulo:'Definir tipo de calefacción',                  faseNum:5, tipo:'definicion',  leadTimeDias:30, responsableTipo:'Proyecto' },
  { codigo:'5.7', titulo:'Comprar equipos A/A y calefacción',            faseNum:5, tipo:'compra',      leadTimeDias:30, responsableTipo:'Admin' },
  { codigo:'5.8', titulo:'Verificar presiones agua y pendientes',        faseNum:5, tipo:'verificacion',leadTimeDias:0,  responsableTipo:'Campo' },
  { codigo:'5.9', titulo:'Registro fotográfico instalaciones',           faseNum:5, tipo:'verificacion',leadTimeDias:0,  responsableTipo:'Campo' },
  // FASE 6
  { codigo:'6.1', titulo:'Revoque grueso interior',                      faseNum:6, tipo:'ejecucion',   leadTimeDias:0,  responsableTipo:'Contratista' },
  { codigo:'6.2', titulo:'Revoque grueso exterior',                      faseNum:6, tipo:'ejecucion',   leadTimeDias:0,  responsableTipo:'Contratista' },
  { codigo:'6.3', titulo:'Contrapiso interior',                          faseNum:6, tipo:'ejecucion',   leadTimeDias:0,  responsableTipo:'Contratista' },
  { codigo:'6.4', titulo:'Carpeta de nivelación',                        faseNum:6, tipo:'ejecucion',   leadTimeDias:0,  responsableTipo:'Contratista' },
  { codigo:'6.5', titulo:'Verificar niveles piso terminado',             faseNum:6, tipo:'verificacion',leadTimeDias:0,  responsableTipo:'Campo' },
  // FASE 7: DEFINICIONES DE DISEÑO (CRÍTICO)
  { codigo:'7.1',  titulo:'Definir pisos',                               faseNum:7, tipo:'definicion',  leadTimeDias:30, responsableTipo:'Proyecto' },
  { codigo:'7.2',  titulo:'Comprar pisos (lote único +10%)',             faseNum:7, tipo:'compra',      leadTimeDias:30, responsableTipo:'Admin' },
  { codigo:'7.3',  titulo:'Definir revestimientos baños',                faseNum:7, tipo:'definicion',  leadTimeDias:30, responsableTipo:'Proyecto' },
  { codigo:'7.4',  titulo:'Comprar revestimientos baños',                faseNum:7, tipo:'compra',      leadTimeDias:30, responsableTipo:'Admin' },
  { codigo:'7.5',  titulo:'Definir griferías y sanitarios',              faseNum:7, tipo:'definicion',  leadTimeDias:21, responsableTipo:'Proyecto' },
  { codigo:'7.6',  titulo:'Comprar griferías y sanitarios',              faseNum:7, tipo:'compra',      leadTimeDias:21, responsableTipo:'Admin' },
  { codigo:'7.7',  titulo:'Definir muebles de cocina',                   faseNum:7, tipo:'definicion',  leadTimeDias:60, responsableTipo:'Proyecto' },
  { codigo:'7.8',  titulo:'Tomar medidas muebles cocina',                faseNum:7, tipo:'verificacion',leadTimeDias:45, responsableTipo:'Campo' },
  { codigo:'7.9',  titulo:'Comprar/encargar muebles cocina',             faseNum:7, tipo:'compra',      leadTimeDias:45, responsableTipo:'Admin' },
  { codigo:'7.10', titulo:'Definir muebles de baño',                     faseNum:7, tipo:'definicion',  leadTimeDias:30, responsableTipo:'Proyecto' },
  { codigo:'7.11', titulo:'Comprar muebles de baño',                     faseNum:7, tipo:'compra',      leadTimeDias:30, responsableTipo:'Admin' },
  { codigo:'7.12', titulo:'Definir puertas interiores',                  faseNum:7, tipo:'definicion',  leadTimeDias:30, responsableTipo:'Proyecto' },
  { codigo:'7.13', titulo:'Comprar puertas interiores',                  faseNum:7, tipo:'compra',      leadTimeDias:30, responsableTipo:'Admin' },
  { codigo:'7.14', titulo:'Definir puerta de entrada',                   faseNum:7, tipo:'definicion',  leadTimeDias:45, responsableTipo:'Proyecto' },
  { codigo:'7.15', titulo:'Comprar puerta de entrada',                   faseNum:7, tipo:'compra',      leadTimeDias:45, responsableTipo:'Admin' },
  { codigo:'7.16', titulo:'Definir mesadas',                             faseNum:7, tipo:'definicion',  leadTimeDias:21, responsableTipo:'Proyecto' },
  { codigo:'7.17', titulo:'Comprar mesadas',                             faseNum:7, tipo:'compra',      leadTimeDias:21, responsableTipo:'Admin' },
  { codigo:'7.18', titulo:'Definir iluminación',                         faseNum:7, tipo:'definicion',  leadTimeDias:14, responsableTipo:'Proyecto' },
  { codigo:'7.19', titulo:'Comprar artefactos iluminación',              faseNum:7, tipo:'compra',      leadTimeDias:14, responsableTipo:'Admin' },
  { codigo:'7.20', titulo:'Definir pintura (colores)',                   faseNum:7, tipo:'definicion',  leadTimeDias:7,  responsableTipo:'Proyecto' },
  { codigo:'7.21', titulo:'Definir timbre/portero/videoportero',         faseNum:7, tipo:'definicion',  leadTimeDias:14, responsableTipo:'Proyecto' },
  { codigo:'7.22', titulo:'Comprar timbre/portero',                      faseNum:7, tipo:'compra',      leadTimeDias:14, responsableTipo:'Admin' },
  { codigo:'7.23', titulo:'Definir escalera (si aplica)',                faseNum:7, tipo:'definicion',  leadTimeDias:45, responsableTipo:'Proyecto' },
  { codigo:'7.24', titulo:'Comprar/encargar escalera',                   faseNum:7, tipo:'compra',      leadTimeDias:45, responsableTipo:'Admin' },
  // FASE 8
  { codigo:'8.1',  titulo:'Colocación de pisos',                         faseNum:8, tipo:'ejecucion',   leadTimeDias:0,  responsableTipo:'Contratista' },
  { codigo:'8.2',  titulo:'Revestimientos de baño',                      faseNum:8, tipo:'ejecucion',   leadTimeDias:0,  responsableTipo:'Contratista' },
  { codigo:'8.3',  titulo:'Revoque fino / yeso',                         faseNum:8, tipo:'ejecucion',   leadTimeDias:0,  responsableTipo:'Contratista' },
  { codigo:'8.4',  titulo:'Colocación de aberturas',                     faseNum:8, tipo:'ejecucion',   leadTimeDias:0,  responsableTipo:'Contratista' },
  { codigo:'8.5',  titulo:'Colocación puertas interiores',               faseNum:8, tipo:'ejecucion',   leadTimeDias:0,  responsableTipo:'Contratista' },
  { codigo:'8.6',  titulo:'Instalación muebles cocina',                  faseNum:8, tipo:'ejecucion',   leadTimeDias:0,  responsableTipo:'Mueblero' },
  { codigo:'8.7',  titulo:'Instalación de mesadas',                      faseNum:8, tipo:'ejecucion',   leadTimeDias:0,  responsableTipo:'Marmolero' },
  { codigo:'8.8',  titulo:'Colocación sanitarios y griferías',           faseNum:8, tipo:'ejecucion',   leadTimeDias:0,  responsableTipo:'Plomero' },
  { codigo:'8.9',  titulo:'Cableado, bocas y tablero',                   faseNum:8, tipo:'ejecucion',   leadTimeDias:0,  responsableTipo:'Electricista' },
  { codigo:'8.10', titulo:'Artefactos de iluminación',                   faseNum:8, tipo:'ejecucion',   leadTimeDias:0,  responsableTipo:'Electricista' },
  { codigo:'8.11', titulo:'Pintura interior',                            faseNum:8, tipo:'ejecucion',   leadTimeDias:0,  responsableTipo:'Pintor' },
  { codigo:'8.12', titulo:'Pintura/revestimiento exterior',              faseNum:8, tipo:'ejecucion',   leadTimeDias:0,  responsableTipo:'Pintor' },
  { codigo:'8.13', titulo:'Zócalos',                                     faseNum:8, tipo:'ejecucion',   leadTimeDias:0,  responsableTipo:'Contratista' },
  { codigo:'8.14', titulo:'Instalación timbre/portero',                  faseNum:8, tipo:'ejecucion',   leadTimeDias:0,  responsableTipo:'Electricista' },
  { codigo:'8.15', titulo:'Verificar bocas eléctricas',                  faseNum:8, tipo:'verificacion',leadTimeDias:0,  responsableTipo:'Campo' },
  { codigo:'8.16', titulo:'Verificar griferías y desagües',              faseNum:8, tipo:'verificacion',leadTimeDias:0,  responsableTipo:'Campo' },
  { codigo:'8.17', titulo:'Prueba hermeticidad gas',                     faseNum:8, tipo:'verificacion',leadTimeDias:0,  responsableTipo:'Gasista' },
  // FASE 9
  { codigo:'9.1', titulo:'Vereda reglamentaria',                         faseNum:9, tipo:'ejecucion',   leadTimeDias:0,  responsableTipo:'Contratista' },
  { codigo:'9.2', titulo:'Solado patios / deck',                         faseNum:9, tipo:'ejecucion',   leadTimeDias:0,  responsableTipo:'Contratista' },
  { codigo:'9.3', titulo:'Parquización / jardín',                        faseNum:9, tipo:'ejecucion',   leadTimeDias:0,  responsableTipo:'Paisajista' },
  { codigo:'9.4', titulo:'Pileta (si aplica)',                           faseNum:9, tipo:'ejecucion',   leadTimeDias:60, responsableTipo:'Pilero' },
  { codigo:'9.5', titulo:'Cerco / medianera',                            faseNum:9, tipo:'ejecucion',   leadTimeDias:0,  responsableTipo:'Contratista' },
  { codigo:'9.6', titulo:'Portón de garage',                             faseNum:9, tipo:'compra',      leadTimeDias:30, responsableTipo:'Admin' },
  // FASE 10
  { codigo:'10.1', titulo:'Limpieza final de obra',                      faseNum:10, tipo:'ejecucion',   leadTimeDias:0,  responsableTipo:'Contratista' },
  { codigo:'10.2', titulo:'Punch list con cliente',                      faseNum:10, tipo:'verificacion',leadTimeDias:0,  responsableTipo:'Director' },
  { codigo:'10.3', titulo:'Corrección detalles punch list',              faseNum:10, tipo:'ejecucion',   leadTimeDias:0,  responsableTipo:'Contratista' },
  { codigo:'10.4', titulo:'Entregar documentación as-built',             faseNum:10, tipo:'definicion',  leadTimeDias:0,  responsableTipo:'Proyecto' },
  { codigo:'10.5', titulo:'Entregar manuales y garantías',               faseNum:10, tipo:'definicion',  leadTimeDias:0,  responsableTipo:'Admin' },
  { codigo:'10.6', titulo:'Tramitar final de obra',                      faseNum:10, tipo:'definicion',  leadTimeDias:30, responsableTipo:'Admin' },
  { codigo:'10.7', titulo:'Entrega formal al cliente',                   faseNum:10, tipo:'verificacion',leadTimeDias:0,  responsableTipo:'Director' },
];
